(executable
 (name test)
 (libraries ocsipersist ocsipersist-sqlite))

(executable
 (name test_functorial)
 (libraries ocsipersist ocsipersist-sqlite))

(executable
 (name test_json)
 (libraries ocsipersist ocsipersist-sqlite js_of_ocaml.deriving)
 (preprocess
  (pps js_of_ocaml-ppx_deriving_json)))
