(library
 (name ocsipersist_lib)
 (public_name ocsipersist-lib)
 (modules ocsipersist_lib)
 (wrapped false)
 (libraries lwt js_of_ocaml.deriving))

(library
 (name ocsipersist)
 (public_name ocsipersist)
 (virtual_modules ocsipersist)
 (modules ocsipersist)
 (libraries ocsipersist_lib lwt js_of_ocaml.deriving))
